
=====
===== LOGGING STARTED Fri Jun  8 02:55:38 -03 2018
=====
Exec: /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app/erts-6.3/bin/erlexec -boot /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app/releases/0.0.2/release_me -boot_var ERTS_LIB_DIR /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app/erts-6.3/../lib -env ERL_LIBS /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app/lib -config /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app/releases/0.0.2/sys.config -pa /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app/lib/consolidated -args_file /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app/releases/0.0.2/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app
/Users/enogrob/THINGS_HOME/Projects/ebook-elixir-cookbook/src/code/chapter6/release_me/tmp/elixir_app
{error_logger,{{2018,6,8},{2,55,38}},"Protocol: ~tp: the name release_me@127.0.0.1 seems to be in use by another Erlang node",["inet_tcp"]}
{error_logger,{{2018,6,8},{2,55,38}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,322}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.109>,<0.17.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,801}],[]]}
{error_logger,{{2018,6,8},{2,55,38}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['release_me@127.0.0.1',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2018,6,8},{2,55,38}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2018,6,8},{2,55,38}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2018,6,8},{2,55,38}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
